export const projects = [
    {
        technologies: [],
        _id: "1",
        title: "PreSellCrm",
        Image: "https://opscale.in/wp-content/uploads/2023/05/CRM-1-e1672583501835.jpg",
        description: "this is a lead genrations to sell a flat  ",
        link: "/",
    },
    {
        technologies: [],
        _id: "2",
        title: "Broker system",
        Image: "https://www.trimurty.com/blog/wp-content/uploads/2017/09/real_estate_agent.jpg",
        description: " this a flat sell via broker system",
        link: "/",
    },
    {
        technologies: [],
        _id: "3",
        title: "Chating interface",
        Image: "https://cdn.dribbble.com/users/5304642/screenshots/13387513/media/feb2d91e9ac44defd8d66536b3f6b013.png?resize=400x300&vertical=center",
        description: " this a flat sell via broker system",
        link: "/",
    },
    {
        technologies: [],
        _id: "4",
        title: "Ma Ananda Moye",
        Image: "https://s3-ap-southeast-1.amazonaws.com/images.brajrasik.org/5e7684fd88897f0062d10726.jpeg",
        description: "This is a Ashram manage and funding magement system",
        link: "/",
    },
    {
        technologies: [],
        _id: "5",
        title: "SOAT",
        Image: "https://www.gisattendance.com/images/new/Slider_1.jpg",
        description: "This a smart Attendance system Through App",
        link: "/",
    },
    {
        technologies: [],
        _id: "6",
        title: "Tasty Heaven",
        Image: "https://tb-static.uber.com/prod/image-proc/processed_images/8647726ea75aae2d959353233575ace6/ec1689ae3a25695f1b8e25c59bec5034.jpeg",
        description: "this a cloud base food order and recive system for a big mall OR a local shop. ",
        link: "/",
    },

]
